---

####################
# Create the namespace
####################

- name: Find out if namespace already exists
  command: "kubectl get ns {{ namespace }} -o json"
  register: get_ns
  ignore_errors: true

- name: Create the namespace
  command: "kubectl create ns {{ namespace }}"
  when: get_ns|failed

# Render templates for resource quotas

- name: Generate compute resources quota
  template:
    src: compute.resourcequota.yaml.j2
    dest: /tmp/compute.resourcequota.yaml
    mode: 0744
  become: false

- name: Generate object quota
  template:
    src: object.resourcequota.yaml.j2
    dest: /tmp/object.resourcequota.yaml
    mode: 0744
  become: false

# Load resource quotas

- name: Find out if quota already exists
  command: "kubectl --namespace {{ namespace }} get resourcequotas compute-quota -o json"
  register: get_resourcequota
  ignore_errors: true

- name: Create the quota
  command: "kubectl --namespace {{ namespace }} create -f /tmp/compute.resourcequota.yaml"
  when: get_resourcequota|failed

- name: Replace the quota
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/compute.resourcequota.yaml"
  when: get_resourcequota|succeeded

- name: Find out if quota already exists
  command: "kubectl --namespace {{ namespace }} get resourcequotas object-quota -o json"
  register: get_objectquota
  ignore_errors: true

- name: Create the quota
  command: "kubectl --namespace {{ namespace }} create -f /tmp/object.resourcequota.yaml"
  when: get_objectquota|failed

- name: Replace the quota
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/object.resourcequota.yaml"
  when: get_objectquota|succeeded
