---

####################
# Create the namespace
####################

- name: Find out if namespace already exists
  command: "kubectl get ns {{ namespace }} -o json"
  register: get_ns
  ignore_errors: true

- name: Create the namespace
  command: "kubectl create ns {{ namespace }}"
  when: get_ns|failed
