global:
  caCertB64Enc: REQUIRED

image:
  repository: dbgdave/dave-store-manager
  tag: master
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

minReplicaCount: 2
maxReplicaCount: 3

apiKeyB64Enc: REQUIRED
apiCertB64Enc: REQUIRED

databaseConnectionUrl: "mongodb://dave-mongo-0.dave-mongo:27017,dave-mongo-1.dave-mongo:27017,dave-mongo-2.dave-mongo:27017/?replicaSet=rs0"
databaseName: DAVe
