---
###########################
# Install DAVe application
###########################

- hosts: localhost
  connection: local
  roles:
    - ca
    - store-manager-certs
    - margin-loader-certs
    - api-certs
    - helm-config
