---

####################
# Install Network Policies
####################

# Isolate network access

- name: Isolate network access
  command: "kubectl annotate ns {{ namespace }} 'net.beta.kubernetes.io/network-policy={\"ingress\":{\"isolation\":\"DefaultDeny\"}}' --overwrite=true"

# Render templates

- name: Generate API network policy
  template:
    src: api-access.network-policy.yaml.j2
    dest: /tmp/api-access.network-policy.yaml
    mode: 0744
  become: false

- name: Generate UI network policy
  template:
    src: ui-access.network-policy.yaml.j2
    dest: /tmp/ui-access.network-policy.yaml
    mode: 0744
  become: false

- name: Generate Store Manager network policy (Other apps access to Store MAnager)
  template:
    src: store-manager.network-policy.yaml.j2
    dest: /tmp/store-manager.network-policy.yaml
    mode: 0744
  become: false

- name: Generate Database network policy (Other apps access to DB)
  template:
    src: mongo-access.network-policy.yaml.j2
    dest: /tmp/mongo-access.network-policy.yaml
    mode: 0744
  become: false

# Add API network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-api-access -o json"
  register: get_np
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-api-access"
  when: get_np|succeeded

- name: Create the network policy
  command: "kubectl --namespace {{ namespace }} create -f /tmp/api-access.network-policy.yaml"

# Add UI network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-ui-access -o json"
  register: get_np
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-ui-access"
  when: get_np|succeeded

- name: Create the network policy
  command: "kubectl --namespace {{ namespace }} create -f /tmp/ui-access.network-policy.yaml"

# Add Store Manager network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-store-manager-access -o json"
  register: get_np
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-store-manager-access"
  when: get_np|succeeded

- name: Create the network policy
  command: "kubectl --namespace {{ namespace }} create -f /tmp/dave-store-manager-access.network-policy.yaml"

# Add Database network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-mongo-access -o json"
  register: get_np
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-mongo-access"
  when: get_np|succeeded

- name: Create the network policy
  command: "kubectl --namespace {{ namespace }} create -f /tmp/mongo-access.network-policy.yaml"
