global:
  caCertB64Enc: REQUIRED

image:
  repository: dbgdave/dave-margin-loader
  tag: master
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

minReplicaCount: 2
maxReplicaCount: 3

sslKeyB64Enc: REQUIRED
sslCertB64Enc: REQUIRED

cilHostname: REQUIRED
cilPort: REQUIRED
cilUsername: REQUIRED
cilPassword: REQUIRED
