---

####################
# Install DAVe-MArginLoader
####################

# Generate the internal SSL key

- name: Render internal SSL template
  template:
    src: dave-margin-loader-ssl.json.j2
    dest: "{{ ca_dir }}/dave-margin-loader-ssl.json"
    mode: 0744
  become: false

- name: Create the internal SSL keys
  shell: "cfssl gencert -ca ca.pem -ca-key ca-key.pem dave-margin-loader-ssl.json | cfssljson -bare dave-margin-loader-ssl"
  args:
    chdir: "{{ ca_dir }}"

- name: Convert PKCS1 to PKCS8
  shell: "openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in dave-margin-loader-ssl-key.pem -out dave-margin-loader-ssl-pkcs8.pem"
  args:
    chdir: "{{ ca_dir }}"

- set_fact:
   dave_margin_loader_ssl_key: "{{ ca_dir }}/dave-margin-loader-ssl-pkcs8.pem"
   dave_margin_loader_ssl_cert: "{{ ca_dir }}/dave-margin-loader-ssl.pem"

# Render templates

- name: Generate config map
  template:
    src: margin-loader.config-map.yaml.j2
    dest: /tmp/margin-loader.config-map.yaml
    mode: 0744
  become: false

- name: Generate secret
  template:
    src: margin-loader.secret.yaml.j2
    dest: /tmp/margin-loader.secret.yaml
    mode: 0744
  become: false

- name: Generate service account
  template:
    src: margin-loader.serviceaccount.yaml.j2
    dest: /tmp/margin-loader.serviceaccount.yaml
    mode: 0744
  become: false

- name: Generate role
  template:
    src: margin-loader.role.yaml.j2
    dest: /tmp/margin-loader.role.yaml
    mode: 0744
  become: false

- name: Generate role binding
  template:
    src: margin-loader.rolebinding.yaml.j2
    dest: /tmp/margin-loader.rolebinding.yaml
    mode: 0744
  become: false

- name: Generate deployment
  template:
    src: margin-loader.deployment.yaml.j2
    dest: /tmp/margin-loader.deployment.yaml
    mode: 0744
  become: false

- name: Generate HPA
  template:
    src: margin-loader.autoscaler.yaml.j2
    dest: /tmp/margin-loader.autoscaler.yaml
    mode: 0744
  become: false

# Add service account

- name: Find out if service account already exists
  command: "kubectl --namespace {{ namespace }} get serviceaccounts dave-margin-loader -o json"
  register: get_serviceaccount
  ignore_errors: true

- name: Create the service account
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.serviceaccount.yaml"
  when: get_serviceaccount|failed

- name: Replace the service account
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.serviceaccount.yaml"
  when: get_serviceaccount|succeeded

- name: Find out if role already exists
  command: "kubectl --namespace {{ namespace }} get role dave-margin-loader -o json"
  register: get_role
  ignore_errors: true

- name: Create the role
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.role.yaml"
  when: get_role|failed

- name: Replace the role
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.role.yaml"
  when: get_role|succeeded

- name: Find out if role binding already exists
  command: "kubectl --namespace {{ namespace }} get rolebinding dave-margin-loader -o json"
  register: get_rolebinding
  ignore_errors: true

- name: Create the role binding
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.rolebinding.yaml"
  when: get_rolebinding|failed

- name: Replace the role binding
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.rolebinding.yaml"
  when: get_rolebinding|succeeded

# Add config-map

- name: Find out if config-map already exists
  command: "kubectl --namespace {{ namespace }} get cm dave-margin-loader -o json"
  register: get_cm
  ignore_errors: true

- name: Create the config-map
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.config-map.yaml"
  when: get_cm|failed

- name: Replace the config-map
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.config-map.yaml"
  when: get_cm|succeeded

# Add secret

- name: Find out if secret already exists
  command: "kubectl --namespace {{ namespace }} get secret dave-margin-loader -o json"
  register: get_secret
  ignore_errors: true

- name: Create the secret
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.secret.yaml"
  when: get_secret|failed

- name: Replace the secret
  command: "kubectl --namespace {{ namespace }} replace -f /tmp/margin-loader.secret.yaml"
  when: get_secret|succeeded

# Add deployment

- name: Find out if deployment already exists
  command: "kubectl --namespace {{ namespace }} get deployment dave-margin-loader -o json"
  register: get_deployment
  ignore_errors: true

- name: Create the deployment
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.deployment.yaml"
  when: get_deployment|failed

- name: Replace the deployment
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.deployment.yaml"
  when: get_deployment|succeeded

# Make sure the deployment is running before moving forward

- name: Verify that all pods are ready
  shell: kubectl --namespace {{ namespace }} get pods | grep "dave-margin-loader" | grep "Running" | wc -l
  register: cmd_result
  until: cmd_result.stdout.find('{{ margin_loader_min_replicas }}') != -1
  retries: 20
  delay: 30

# Add autoscaler

- name: Find out if HPA already exists
  command: "kubectl --namespace {{ namespace }} get hpa dave-margin-loader -o json"
  register: get_hpa
  ignore_errors: true

- name: Create the HPA
  command: "kubectl --namespace {{ namespace }} create -f /tmp/margin-loader.autoscaler.yaml"
  when: get_hpa|failed

- name: Replace the HPA
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/margin-loader.autoscaler.yaml"
  when: get_hpa|succeeded
