apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dave-store-manager
  labels:
    app: dave
    layer: db
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.min_replicas }}
  template:
    metadata:
      name: dave-store-manager
      labels:
        name: dave-store-manager
        app: dave
        layer: db
        project: dave
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/dave-store-manager: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/dave-store-manager: docker/default
    spec:
      serviceAccount: dave-store-manager
      containers:
        - image: dbgdave/dave-store-manager:{{ .Values.release }}
          name: dave-store-manager
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: dave-store-manager
                  key: java.opts
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dave-store-manager
                  key: log.level
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: dave-store-manager
                  key: mongo.name
            - name: MONGO_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: dave-store-manager
                  key: mongo.connection_url
            - name: API_SSL_REQUIRE_CLIENT_AUTH
              valueFrom:
                configMapKeyRef:
                  name: dave-store-manager
                  key: api.ssl_require_client_auth
            - name: API_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: dave-store-manager
                  key: api.ssl_cert
            - name: API_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: dave-store-manager
                  key: api.ssl_key
            - name: API_SSL_TRUST_CERTS
              valueFrom:
                secretKeyRef:
                  name: dave-store-manager
                  key: api.ssl_trust_certs
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
