# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: db
    project: dave
data:
  api.ssl_key: {{ .Values.apiKeyB64Enc }}
  api.ssl_cert: {{ .Values.apiCertB64Enc }}
  api.ssl_trust_certs: {{ .Values.global.caCertB64Enc }}
