# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: dave-store-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: db
    project: dave
data:
  api.ssl_key: {{ .Values.api_key_b64enc }}
  api.ssl_cert: {{ .Values.api_cert_b64enc }}
  api.ssl_trust_certs: {{ .Values.global.ca_cert_b64enc }}
