apiVersion: v1
kind: Service
metadata:
  labels:
    app: dave
    layer: db
    project: dave
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: {{ .Chart.Name }}
  type: ClusterIP
