apiVersion: v1
kind: Service
metadata:
  labels:
{{ toYaml .Values.labels | indent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: {{ .Chart.Name }}
  type: ClusterIP
