apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-store-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: db
    project: dave
data:
  java.opts: "-Xmx512m -XX:MaxDirectMemorySize=1024m"
  log.level: "INFO"
  mongo.name: {{ .Values.database_name | quote }}
  mongo.connection_url: {{ .Values.database_connection_url | quote }}
  api.ssl_require_client_auth: "true"
