apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicaCount }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
{{ toYaml .Values.labels | indent 8 }}
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/{{ .Chart.Name }}: docker/default
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: java.opts
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: log.level
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: mongo.name
            - name: MONGO_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: mongo.connection_url
            - name: API_SSL_REQUIRE_CLIENT_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_require_client_auth
            - name: API_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_cert
            - name: API_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_key
            - name: API_SSL_TRUST_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_trust_certs
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
