apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-provisioning
  labels:
    app: mongo-provisioning
    layer: db
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: mongo-provisioning
        layer: db
        project: dave
    spec:
      containers:
      - image: {{ .Values.images.dbRestore.repository }}:{{ .Values.images.dbRestore.tag }}
        name: {{ .Chart.Name }}-restore
        imagePullPolicy: {{ .Values.images.dbRestore.pullPolicy }}
        volumeMounts:
          - mountPath: /db
            name: db-volume
          - mountPath: /restore-script
            name: restore-script-volume
        resources:
          requests:
            cpu: {{ .Values.resources.dbRestore.requests.cpu }}
            memory: {{ .Values.resources.dbRestore.requests.memory }}
          limits:
            cpu: {{ .Values.resources.dbRestore.limits.cpu }}
            memory: {{ .Values.resources.dbRestore.limits.memory }}
        command: ["bash", "restore-script/mongo-restore.sh"]
      initContainers:
      - image: {{ .Values.images.dbDownload.repository }}:{{ .Values.images.dbDownload.tag }}
        name: {{ .Chart.Name }}-download
        imagePullPolicy: {{ .Values.images.dbDownload.pullPolicy }}
        volumeMounts:
          - mountPath: /db
            name: db-volume
        resources:
          requests:
            cpu: {{ .Values.resources.dbDownload.requests.cpu }}
            memory: {{ .Values.resources.dbDownload.requests.memory }}
          limits:
            cpu: {{ .Values.resources.dbDownload.limits.cpu }}
            memory: {{ .Values.resources.dbDownload.limits.memory }}
        command: ["wget",  {{ .Values.db_unload_url | quote }}, "-O", "/db/db.tar.gz"]
      volumes:
        - name: db-volume
          emptyDir: {}
        - name: restore-script-volume
          configMap:
            name: restore-script-volume 
      restartPolicy: Never
