global:
  uiDns: ui.risk.dev.dbgcloud.io
  apiDns: api.risk.dev.dbgcloud.io
  useInternalLoadBalancer: true
  internalLoadBalancerIp: 0.0.0.0/0
  authDns: auth.dave.dbg-devops.com
  authClientId: dave-ui
  authWellKnownEndpoint: /auth/realms/DAVe/.well-known/openid-configuration

image:
  repository: dbgdave/dave-ui
  tag: master
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 128Mi

minReplicaCount: 2
maxReplicaCount: 3

authFlow: openid-connect/direct
authScopes: "['profile']"

uiKeyB64Enc: REQUIRED
uiCertB64Enc: REQUIRED
