apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  dave.api: "https://{{ .Values.global.api_dns }}"
  dave.auth_well_known: "https://{{ .Values.global.auth_dns }}{{ .Values.global.auth_well_known_endpoint }}"
  dave.auth_client_id: "{{ .Values.global.auth_client_id }}"
  dave.auth_flow: "{{ .Values.auth_flow }}"
  dave.auth_scopes: "{{ .Values.auth_scopes }}"
  http.compression: "1"
