apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  dave.api: "https://{{ .Values.global.apiDns }}"
  dave.auth_well_known: "https://{{ .Values.global.authDns }}{{ .Values.global.authWellKnownEndpoint }}"
  dave.authClientId: "{{ .Values.global.authClientId }}"
  dave.authFlow: "{{ .Values.authFlow }}"
  dave.authScopes: "{{ .Values.authScopes }}"
  http.compression: "1"
