apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicaCount }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
{{ toYaml .Values.labels | indent 8 }}
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/{{ .Chart.Name }}: docker/default
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
          env:
            - name: DAVE_REST_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dave.api
            - name: DAVE_AUTH_WELL_KNOWN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dave.auth_well_known
            - name: DAVE_AUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dave.authClientId
            - name: DAVE_AUTH_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dave.authScopes
            - name: DAVE_AUTH_FLOW
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dave.authFlow
            - name: DAVE_HTTP_COMPRESSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: http.compression
            - name: DAVE_HTTP_SSL_SERVER_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: http.public_key
            - name: DAVE_HTTP_SSL_SERVER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: http.private_key
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
