apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dave-ui
  labels:
    app: dave
    layer: frontend
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.min_replicas }}
  template:
    metadata:
      name: dave-ui
      labels:
        name: dave-ui
        app: dave
        layer: frontend
        project: dave
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/dave-ui: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/dave-ui: docker/default
    spec:
      serviceAccount: dave-ui
      containers:
        - image: dbgdave/dave-ui:{{ .Values.release }}
          name: dave-ui
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 128Mi
          env:
            - name: DAVE_REST_URL
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: dave.api
            - name: DAVE_AUTH_WELL_KNOWN_URL
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: dave.auth_well_known
            - name: DAVE_AUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: dave.auth_client_id
            - name: DAVE_AUTH_SCOPES
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: dave.auth_scopes
            - name: DAVE_AUTH_FLOW
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: dave.auth_flow
            - name: DAVE_HTTP_COMPRESSION
              valueFrom:
                configMapKeyRef:
                  name: dave-ui
                  key: http.compression
            - name: DAVE_HTTP_SSL_SERVER_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: dave-ui
                  key: http.public_key
            - name: DAVE_HTTP_SSL_SERVER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: dave-ui
                  key: http.private_key
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
