# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: dave-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  http.private_key: {{ .Values.ui_key_b64enc }}
  http.public_key: {{ .Values.ui_cert_b64enc }}
