apiVersion: v1
kind: Service
metadata:
  labels:
    app: dave
    layer: frontend
    project: dave
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.uiDns }}.
    {{- if .Values.global.useInternalLoadBalancer }}
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .Values.global.internalLoadBalancerIp | quote }}
    {{- end }}
  name: dave-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: dave-ui
  type: LoadBalancer
