# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
data:
  http.private_key: {{ .Values.uiKeyB64Enc }}
  http.public_key: {{ .Values.uiCertB64Enc }}
