---

####################
# Install Mongo DB
####################

# Render templates

- name: Generate service
  template:
    src: mongo.service.yaml.j2
    dest: /tmp/mongo.service.yaml
    mode: 0744
  become: false

- name: Generate stateful set
  template:
    src: mongo.statefulset.yaml.j2
    dest: /tmp/mongo.statefulset.yaml
    mode: 0744
  become: false

# Add service

- name: Find out if service already exists
  command: "kubectl --namespace {{ namespace }} get service dave-mongo -o json"
  register: get_service
  ignore_errors: true

- name: Create the service
  command: "kubectl --namespace {{ namespace }} create -f /tmp/mongo.service.yaml"
  when: get_service|failed

- name: Replace the service
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/mongo.service.yaml"
  when: get_service|succeeded

# Add statefulset

- name: Find out if statefulset already exists
  command: "kubectl --namespace {{ namespace }} get statefulset dave-mongo -o json"
  register: get_statefulset
  ignore_errors: true

- name: Create the statefulset
  command: "kubectl --namespace {{ namespace }} create -f /tmp/api.statefulset.yaml"
  when: get_statefulset|failed

- name: Replace the statefulset
  command: "kubectl --namespace {{ namespace }} apply -f /tmp/api.statefulset.yaml"
  when: get_statefulset|succeeded
