global:
  apiDns: api.risk.dev.dbgcloud.io
  useInternalLoadBalancer: true
  internalLoadBalancerIp: 0.0.0.0/0
  caCertB64Enc: REQUIRED

image:
  repository: dbgdave/dave-api
  tag: master
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

minReplicaCount: 2
maxReplicaCount: 3

apiKeyB64Enc: REQUIRED
apiCertB64Enc: REQUIRED
sslKeyB64Enc: REQUIRED
sslCertB64Enc: REQUIRED
