---

####################
# Provision Mongo database
####################

# Download the file

- name: Download database unload
  get_url:
    url: "{{ db_unload_url }}"
    dest: /tmp/mongo.backup.tar.gz
    mode: 0744
  when:
    - db_unload_url is defined
    - dabatase_url is undefined

# Copy the file

- name: Find out if config-map already exists
  command: "kubectl cp /tmp/mongo.backup.tar.gz {{ namespace }}/dave-mongo:/tmp/mongo.backup.tar.gz --container mongo"
  when:
    - db_unload_url is defined
    - dabatase_url is undefined

# Unpack and load the file into database

- name: Find out if config-map already exists
  command: "kubectl --namespace {{ namespace }} dave-mongo -t --container tar -z -xf /tmp/mongo.backup.tar.gz && mongorestore -d {{ database_name }} ./backup"
  when:
    - db_unload_url is defined
    - dabatase_url is undefined
