---

####################
# Delete DAVe Store Manager
####################

# Delete service

- name: Find out if service already exists
  command: "kubectl --namespace {{ namespace }} get service dave-store-manager -o json"
  register: get_service
  ignore_errors: true

- name: Delete the service
  command: "kubectl --namespace {{ namespace }} delete service dave-store-manager"
  when: get_service|succeeded

# Delete deployment

- name: Find out if deployment already exists
  command: "kubectl --namespace {{ namespace }} get deployment dave-store-manager -o json"
  register: get_deployment
  ignore_errors: true

- name: Delete the deployment
  command: "kubectl --namespace {{ namespace }} delete deployment dave-store-manager"
  when: get_deployment|succeeded

# Delete config-map

- name: Find out if config-map already exists
  command: "kubectl --namespace {{ namespace }} get cm dave-store-manager -o json"
  register: get_cm
  ignore_errors: true

- name: Delete the config-map
  command: "kubectl --namespace {{ namespace }} delete cm dave-store-manager"
  when: get_cm|succeeded

# Delete secret

- name: Find out if secret already exists
  command: "kubectl --namespace {{ namespace }} get secret dave-store-manager -o json"
  register: get_secret
  ignore_errors: true

- name: Delete the secret
  command: "kubectl --namespace {{ namespace }} delete secret dave-store-manager"
  when: get_secret|succeeded

# Delete service account

- name: Find out if service account already exists
  command: "kubectl --namespace {{ namespace }} get serviceaccounts dave-store-manager -o json"
  register: get_serviceaccount
  ignore_errors: true

- name: Delete the service account
  command: "kubectl --namespace {{ namespace }} delete serviceaccounts dave-store-manager"
  when: get_serviceaccount|succeeded
