apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
    app: mongo
    layer: db
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
    layer: db
    project: dave
