apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Chart.Name }}"
  replicas: 3
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
{{ toYaml .Values.labels | indent 8 }}
    spec:
      serviceAccount: {{ .Chart.Name }}
      terminationGracePeriodSeconds: 10
      containers:
        - image: {{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        {{- if .Values.resources.mongo }}
          resources:
{{ toYaml .Values.resources.mongo | indent 12 }}
        {{- end }}
        - image: {{ .Values.images.mongoSidecar.repository }}:{{ .Values.images.mongoSidecar.tag }}
          name: {{ .Chart.Name }}-sidecar
          imagePullPolicy: {{ .Values.images.mongoSidecar.pullPolicy }}
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: {{ include "sidecar.labels" . }}
            - name: KUBE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
        {{- if .Values.resources.mongoSidecar }}
          resources:
{{ toYaml .Values.resources.mongoSidecar | indent 12 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
