apiVersion: v1
kind: Service
metadata:
  name: dave-mongo
  labels:
    name: dave-mongo
    app: mongo
    layer: db
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
    layer: db
    project: dave
