apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dave-mongo-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dave-mongo
subjects:
  - kind: ServiceAccount
    name: dave-mongo
    namespace: {{ .Release.Namespace }}
