apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: mongo
    layer: db
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Chart.Name }}"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
        layer: db
        project: dave
    spec:
      serviceAccount: {{ .Chart.Name }}
      terminationGracePeriodSeconds: 10
      containers:
        - image: {{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: {{ .Values.resources.mongo.requests.cpu }}
              memory: {{ .Values.resources.mongo.requests.memory }}
            limits:
              cpu: {{ .Values.resources.mongo.limits.cpu }}
              memory: {{ .Values.resources.mongo.limits.memory }}
        - image: {{ .Values.images.mongoSidecar.repository }}:{{ .Values.images.mongoSidecar.tag }}
          name: {{ .Chart.Name }}-sidecar
          imagePullPolicy: {{ .Values.images.mongoSidecar.pullPolicy }}
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongo,layer=db,project=dave"
            - name: KUBE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.mongoSidecar.requests.cpu }}
              memory: {{ .Values.resources.mongoSidecar.requests.memory }}
            limits:
              cpu: {{ .Values.resources.mongoSidecar.limits.cpu }}
              memory: {{ .Values.resources.mongoSidecar.limits.memory }}
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
