---

####################
# Create DAVE CA for securing the communication between services
####################

# Render templates

- name: Create CA directory
  file: path={{ certsInternal }} state=directory

- name: Render CA template
  template:
    src: ca.json.j2
    dest: "{{ certsInternal }}/ca.json"
  become: false

# Generate the CA

- stat:
    path: "{{ certsInternal }}/ca.pem"
  register: ca_key

- name: Generate the CA
  shell: "cfssl genkey -initca ca.json | cfssljson -bare ca"
  args:
    chdir: "{{ certsInternal }}"
  when: not ca_key.stat.exists

- set_fact:
    ca_public_key: "{{ certsInternal }}/ca.pem"
