kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: dave-api-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: dave
      layer: api
      project: dave
  ingress:
    - from:
#      - podSelector:
#          matchLabels:
#            run: busybox
