{{- $api := index .Values "dave-api" }}
{{- $apiRequests := $api.resources.requests }}
{{- $apiLimits := $api.resources.limits }}
{{- $apiMaxReplicaCount := $api.maxReplicaCount }}
{{- $apiRequestsCPU := mul (include "cpuToMilliCPU" $apiRequests) $apiMaxReplicaCount }}
{{- $apiLimitsCPU := mul (include "cpuToMilliCPU" $apiLimits) $apiMaxReplicaCount }}
{{- $apiRequestsMemory := mul (include "memoryToBytes" $apiRequests) $apiMaxReplicaCount }}
{{- $apiLimitsMemory := mul (include "memoryToBytes" $apiLimits) $apiMaxReplicaCount }}

{{- $marginLoader := index .Values "dave-margin-loader" }}
{{- $marginLoaderRequests := $marginLoader.resources.requests }}
{{- $marginLoaderLimits := $marginLoader.resources.limits }}
{{- $marginLoaderMaxReplicaCount := $marginLoader.maxReplicaCount }}
{{- $marginLoaderRequestsCPU := mul (include "cpuToMilliCPU" $marginLoaderRequests) $marginLoaderMaxReplicaCount }}
{{- $marginLoaderLimitsCPU := mul (include "cpuToMilliCPU" $marginLoaderLimits) $marginLoaderMaxReplicaCount }}
{{- $marginLoaderRequestsMemory := mul (include "memoryToBytes" $marginLoaderRequests) $marginLoaderMaxReplicaCount }}
{{- $marginLoaderLimitsMemory := mul (include "memoryToBytes" $marginLoaderLimits) $marginLoaderMaxReplicaCount }}

{{- $storeManager := index .Values "dave-store-manager" }}
{{- $storeManagerRequests := $storeManager.resources.requests }}
{{- $storeManagerLimits := $storeManager.resources.limits }}
{{- $storeManagerMaxReplicaCount := $storeManager.maxReplicaCount }}
{{- $storeManagerRequestsCPU := mul (include "cpuToMilliCPU" $storeManagerRequests) $storeManagerMaxReplicaCount }}
{{- $storeManagerLimitsCPU := mul (include "cpuToMilliCPU" $storeManagerLimits) $storeManagerMaxReplicaCount }}
{{- $storeManagerRequestsMemory := mul (include "memoryToBytes" $storeManagerRequests) $storeManagerMaxReplicaCount }}
{{- $storeManagerLimitsMemory := mul (include "memoryToBytes" $storeManagerLimits) $storeManagerMaxReplicaCount }}

{{- $ui := index .Values "dave-ui" }}
{{- $uiRequests := $ui.resources.requests }}
{{- $uiLimits := $ui.resources.limits }}
{{- $uiMaxReplicaCount := $ui.maxReplicaCount }}
{{- $uiRequestsCPU := mul (include "cpuToMilliCPU" $uiRequests) $uiMaxReplicaCount }}
{{- $uiLimitsCPU := mul (include "cpuToMilliCPU" $uiLimits) $uiMaxReplicaCount }}
{{- $uiRequestsMemory := mul (include "memoryToBytes" $uiRequests) $uiMaxReplicaCount }}
{{- $uiLimitsMemory := mul (include "memoryToBytes" $uiLimits) $uiMaxReplicaCount }}


{{- $mongoResources := index .Values "dave-mongo" "resources" }}
{{- $mongoPodsCount := 6 }}

{{- $mongoRequests := $mongoResources.mongo.requests }}
{{- $mongoLimits := $mongoResources.mongo.limits }}
{{- $mongoRequestsCPU := mul (include "cpuToMilliCPU" $mongoRequests) 3 }}
{{- $mongoLimitsCPU := mul (include "cpuToMilliCPU" $mongoLimits) 3 }}
{{- $mongoRequestsMemory := mul (include "memoryToBytes" $mongoRequests) 3 }}
{{- $mongoLimitsMemory := mul (include "memoryToBytes" $mongoLimits) 3 }}

{{- $mongoSideCarRequests := $mongoResources.mongoSidecar.requests }}
{{- $mongoSideCarLimits := $mongoResources.mongoSidecar.limits }}
{{- $mongoSideCarRequestsCPU := mul (include "cpuToMilliCPU" $mongoSideCarRequests) 3 }}
{{- $mongoSideCarLimitsCPU := mul (include "cpuToMilliCPU" $mongoSideCarLimits) 3 }}
{{- $mongoSideCarRequestsMemory := mul (include "memoryToBytes" $mongoSideCarRequests) 3 }}
{{- $mongoSideCarLimitsMemory := mul (include "memoryToBytes" $mongoSideCarLimits) 3 }}

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Chart.Name }}-resource-quota
spec:
  hard:
    services: 4
    pods: {{ add $apiMaxReplicaCount $marginLoaderMaxReplicaCount $storeManagerMaxReplicaCount $uiMaxReplicaCount $mongoPodsCount }}
    requests.cpu: {{ add $apiRequestsCPU $marginLoaderRequestsCPU $storeManagerRequestsCPU $uiRequestsCPU $mongoRequestsCPU $mongoSideCarRequestsCPU }}m
    requests.memory: {{ add $apiRequestsMemory $marginLoaderRequestsMemory $storeManagerRequestsMemory $uiRequestsMemory $mongoRequestsMemory $mongoSideCarRequestsMemory }}
    limits.cpu: {{ add $apiLimitsCPU $marginLoaderLimitsCPU $storeManagerLimitsCPU $uiLimitsCPU $mongoLimitsCPU $mongoSideCarLimitsCPU }}m
    limits.memory: {{ add $apiLimitsMemory $marginLoaderLimitsMemory $storeManagerLimitsMemory $uiLimitsMemory $mongoLimitsMemory $mongoSideCarLimitsMemory }}
