kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Chart.Name }}-store-manager-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: dave
      layer: db
      project: dave
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: dave
            layer: api
            project: dave
      - podSelector:
          matchLabels:
            app: dave
            layer: loader
            project: dave
