kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: dave-ui-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: dave
      layer: frontend
      project: dave
  ingress:
    - from:
#      - podSelector:
#          matchLabels:
#            app: dave
#            layer: api
