---

####################
# Delete Mongo DB
####################

# Delete service

- name: Find out if service already exists
  command: "kubectl --namespace {{ namespace }} get service dave-mongo -o json"
  register: get_service
  ignore_errors: true

- name: Replace the service
  command: "kubectl --namespace {{ namespace }} delete service dave-mongo"
  when: get_service|succeeded

# Delete statefulset

- name: Find out if statefulset already exists
  command: "kubectl --namespace {{ namespace }} get statefulset dave-mongo -o json"
  register: get_statefulset
  ignore_errors: true

- name: Replace the statefulset
  command: "kubectl --namespace {{ namespace }} delete statefulset dave-mongo"
  when: get_statefulset|succeeded

# Delete pods

- name: Find out if pods exist
  command: "kubectl --namespace {{ namespace }} get pods -l project=dave -l app=mongo -l layer=db -o json"
  register: get_pvc
  ignore_errors: true

- name: Replace the pods
  command: "kubectl --namespace {{ namespace }} delete pods -l project=dave -l app=mongo -l layer=db"
  when: get_pvc|succeeded

# Delete persisiten volume claims

- name: Find out if persisiten volume claims exists
  command: "kubectl --namespace {{ namespace }} get pvc -l project=dave -l app=mongo -l layer=db -o json"
  register: get_pvc
  ignore_errors: true

- name: Replace the persisiten volume claims
  command: "kubectl --namespace {{ namespace }} delete pvc -l project=dave -l app=mongo -l layer=db"
  when: get_pvc|succeeded

# Delete service account

- name: Find out if service account already exists
  command: "kubectl --namespace {{ namespace }} get serviceaccounts dave-mongo -o json"
  register: get_serviceaccount
  ignore_errors: true

- name: Delete the service account
  command: "kubectl --namespace {{ namespace }} delete serviceaccounts dave-mongo"
  when: get_serviceaccount|succeeded
