apiVersion: v1
kind: Service
metadata:
  labels:
    app: dave
    layer: api
    project: dave
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.api_dns }}.
    {{- if .Values.global.use_internal_load_balancer }}
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .Values.global.internal_load_balancer_ip | quote }}
    {{- end }}
  name: dave-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: dave-api
  type: LoadBalancer
