apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: dave
    layer: api
    project: dave
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicaCount }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
        app: dave
        layer: api
        project: dave
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/{{ .Chart.Name }}: docker/default
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: java.opts
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: log.level
            - name: API_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.auth
            - name: API_AUTH_WELL_KNOWN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.auth_well_known
            - name: API_AUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.authClientId
            - name: API_CSRF
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.csfr
            - name: API_CSRF_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.csrf_secret
            - name: API_SSL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl
            - name: API_SSL_CLIENT_AUTH
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_client_auth
            - name: API_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_cert
            - name: API_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.ssl_key
            - name: API_COMPRESSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.compression
            - name: API_CORS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.cors
            - name: API_CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: api.cors_origin
            - name: STOREMANAGER_HOSTNAME
              value: dave-store-manager
            - name: STOREMANAGER_PORT
              value: "443"
            - name: STOREMANAGER_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_key
            - name: STOREMANAGER_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_cert
            - name: STOREMANAGER_SSL_TRUST_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_trust_certs
            - name: STOREMANAGER_SSL_VERIFY_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_verify_host
          ports:
            - containerPort: 8443
              name: https
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
