apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: api
    project: dave
data:
  java.opts: "-Xmx768m"
  log.level: "INFO"
  api.ssl: "true"
  api.ssl_client_auth: "false"
  api.compression: "true"
  api.auth: "true"
  api.auth_well_known: "https://{{ .Values.global.authDns }}{{ .Values.global.authWellKnownEndpoint }}"
  api.authClientId: "{{ .Values.global.authClientId }}"
  api.cors: "true"
  api.cors_origin: "*"
  api.csfr: "true"
  storemanager.ssl_verify_host: "false"
