apiVersion: v1
kind: Service
metadata:
  labels:
    app: dave
    layer: api
    project: dave
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.apiDns }}.
    {{- if .Values.global.useInternalLoadBalancer }}
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .Values.global.internalLoadBalancerIp | quote }}
    {{- end }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    name: {{ .Chart.Name }}
  type: LoadBalancer
