# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: dave-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: api
    project: dave
data:
  api.ssl_key: {{ .Values.api_key_b64enc }}
  api.ssl_cert: {{ .Values.api_cert_b64enc }}
  api.csrf_secret: {{ "a15dd14e-243d-11e7-83c4-74d435b8cb4aa15dd14e-243d-11e7-83c4-74d435b8cb4a" | b64enc }}
  storemanager.ssl_key: {{ .Values.ssl_key_b64enc }}
  storemanager.ssl_cert: {{ .Values.ssl_cert_b64enc }}
  storemanager.ssl_trust_certs: {{ .Values.global.ca_cert_b64enc }}
