# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: dave-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: api
    project: dave
data:
  api.ssl_key: {{ .Values.apiKeyB64Enc }}
  api.ssl_cert: {{ .Values.apiCertB64Enc }}
  api.csrf_secret: {{ "a15dd14e-243d-11e7-83c4-74d435b8cb4aa15dd14e-243d-11e7-83c4-74d435b8cb4a" | b64enc }}
  storemanager.ssl_key: {{ .Values.sslKeyB64Enc }}
  storemanager.ssl_cert: {{ .Values.sslCertB64Enc }}
  storemanager.ssl_trust_certs: {{ .Values.global.caCertB64Enc }}
