{{- if .Values.deploy -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: dave
    layer: loader
    project: dave
  namespace: {{ .Release.Namespace }}
{{- end -}}
