{{- if .Values.deploy -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicaCount }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
{{ toYaml .Values.labels | indent 8 }}
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
      #  container.apparmor.seccomp.beta.kubernetes.io/{{ .Chart.Name }}: docker/default
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: java.opts
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: log.level
            - name: AMQP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: margin_loader.amqp_hostname
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: margin_loader.amqp_port
            - name: AMQP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: margin_loader.amqp_username
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: margin_loader.amqp_password
            - name: STOREMANAGER_HOSTNAME
              value: {{ .Chart.Name }}
            - name: STOREMANAGER_PORT
              value: "443"
            - name: STOREMANAGER_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_key
            - name: STOREMANAGER_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_cert
            - name: STOREMANAGER_SSL_TRUST_CERTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: storemanager.ssl_trust_certs
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
{{- end -}}
