{{- if .Values.deploy -}}
# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
data:
  margin_loader.amqp_password: {{ .Values.cilPassword | b64enc }}
  storemanager.ssl_key: {{ .Values.sslKeyB64Enc }}
  storemanager.ssl_cert: {{ .Values.sslCertB64Enc }}
  storemanager.ssl_trust_certs: {{ .Values.global.caCertB64Enc }}
{{- end -}}
