# The secrets should be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: dave-margin-loader
  namespace: {{ .Release.Namespace }}
  labels:
    app: dave
    layer: loader
    project: dave
data:
  margin_loader.amqp_password: {{ .Values.cil_password | b64enc }}
  storemanager.ssl_key: {{ .Values.ssl_key_b64enc }}
  storemanager.ssl_cert: {{ .Values.ssl_cert_b64enc }}
  storemanager.ssl_trust_certs: {{ .Values.global.ca_cert_b64enc }}
