{{- if .Values.deploy -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
data:
  java.opts: "-Xmx768m -XX:MaxDirectMemorySize=768m"
  log.level: "INFO"
  margin_loader.amqp_username: {{ .Values.cilUsername | quote }}
  margin_loader.amqp_hostname: {{ .Values.cilHostname | quote }}
  margin_loader.amqp_port: {{ .Values.cilPort | quote }}
{{- end -}}