{{- if .Values.deploy -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: dave
    layer: loader
    project: dave
  namespace: {{ .Release.Namespace }}
rules:
{{- end -}}
