---

####################
# Delete Network Policies
####################

# Delete API network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-api-access -o json"
  register: get_service
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-api-access"
  when: get_service|succeeded

# Delete UI network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-ui-access -o json"
  register: get_service
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-ui-access"
  when: get_service|succeeded

# Delete Store Manager network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-store-manager-access -o json"
  register: get_service
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-store-manager-access"
  when: get_service|succeeded

# Delete Database network policy

- name: Find out if network policy already exists
  command: "kubectl --namespace {{ namespace }} get networkpolicy dave-mongo-access -o json"
  register: get_service
  ignore_errors: true

- name: Delete the network policy (policies cannot be replaced or modified)
  command: "kubectl --namespace {{ namespace }} delete networkpolicy dave-mongo-access"
  when: get_service|succeeded
